name: 'Coana Vulnerability Analysis'
description: 'Run the Coana CLI tool to extract vulnerability information and publish it to the Coana Dashboard'
inputs:
  apiKey:
    description: 'API key for coana (get one from https://app.coana.tech/dashboard/settings)'
    required: true
  path:
    description: 'Path to root of the project to analyze'
    required: false
    default: '.'
  debug:
    description: 'Enable debug logging'
    default: 'false'
    required: false
  repoUrl:
    description: 'URL of the repository (either that or the project name is required)'
    required: false
  projectName:
    description: 'Project name (either that or the repository url is required)'
    required: false
  timeout:
    description: 'Set a timeout for the Coana backend APIs (defaults to 60 seconds)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apiKey }}
    - ${{ inputs.path }}
    - ${{ inputs.debug }}
    - ${{ inputs.repoUrl }}
    - ${{ inputs.projectName }}
    - ${{ inputs.timeout }}